packages:
  - "apps/jamtools"
  - "apps/small_apps"
  - "apps/vite-test"
  - "packages/jamtools/core"
  - "packages/jamtools/features"
  - "packages/springboard"
  - "packages/springboard/cli"
  - "packages/springboard/create-springboard-app"
  - "packages/springboard/vite-plugin"
  - "packages/springboard/plugins/*"
  - "packages/springboard/external/*"
  - "packages/*"
  - "configs"
catalog:
  # React Ecosystem
  react: "19.2.0"
  react-dom: "19.2.0"
  "@types/react": "19.2.6"
  "@types/react-dom": "19.2.3"
  "react-router": "7.9.6"

  # State Management & Reactive Programming
  rxjs: "7.8.1"
  immer: "10.1.1"

  # RPC & Communication
  json-rpc-2.0: "1.7.1"
  reconnecting-websocket: "4.4.0"
  ws: "8.18.3"

  # Server & API
  hono: "4.6.17"

  # Validation & Data
  zod: "3.25.7"

  # Build Tools & Bundlers
  esbuild: "0.27.0"
  vite: "7.3.0"
  estree-walker: "2.0.2"

  # TypeScript & Types
  typescript: "5.9.3"
  tslib: "2.8.1"
  "@types/node": "20.17.48"
  "@types/better-sqlite3": "7.6.13"

  # CLI & Utilities
  commander: "12.1.0"

  # UI Frameworks
  svelte: "5.43.11"

  # Tauri Desktop
  "@tauri-apps/api": "2.9.0"
  "@tauri-apps/cli": "2.9.4"
  "@tauri-apps/plugin-shell": "2.3.3"
  "@tauri-apps/plugin-dialog": "2.4.2"
  "@tauri-apps/plugin-fs": "2.4.4"
