packages:
  - "apps/jamtools"
  - "apps/small_apps"
  - "packages/jamtools/core"
  - "packages/jamtools/features"
  - "packages/springboard/platforms/node"
  - "packages/springboard/platforms/tauri"
  - "packages/springboard/platforms/webapp"
  - "packages/springboard/platforms/partykit"
  - "packages/springboard/platforms/react-native"
  - "packages/springboard/plugins/*"
  - "packages/springboard/*"
  - "packages/springboard/external/*"
  - "packages/*"
  - "configs"
catalog:
  react: "19.2.0"
  react-dom: "19.2.0"
  "@types/react": "19.2.6"
  "@types/react-dom": "19.2.3"
  rxjs: "7.8.1"
  immer: "10.1.1"
  json-rpc-2.0: "1.7.1"
  reconnecting-websocket: "4.4.0"
  commander: "12.1.0"
  tslib: "2.8.1"
  "@types/node": "20.17.48"
  hono: "4.6.17"
  zod: "3.25.7"
  "react-router": "7.9.6"
  esbuild: "0.27.0"
  estree-walker: "2.0.2"
  typescript: "5.9.3"
  vite: "5.4.19"
  svelte: "5.43.11"
  "@tauri-apps/api": "2.9.0"
  "@tauri-apps/plugin-shell": "2.3.3"
  "@types/better-sqlite3": "7.6.13"
  ws: "8.18.3"
