import { serve } from '@hono/node-server';
import type { Server } from 'node:http';
import { initApp, makeWebsocketServerCoreDependenciesWithSqlite } from 'springboard/server';
import { startNodeApp } from 'springboard/platforms/node';
import '__USER_ENTRY__';

/**
 * Node.js server entrypoint with HMR support
 *
 * This file is generated by the Springboard Vite plugin and serves as the
 * entry point for the Node.js dev server. It:
 *
 * 1. Imports the user's application entry (which registers modules)
 * 2. Exports start/stop functions for lifecycle management
 * 3. Supports HMR via import.meta.hot.dispose()
 */

let server: Server | null = null;

/**
 * Start the node server
 */
export async function start() {
  // If server is already running, stop it first
  if (server) {
    await stop();
  }

  try {
    // Create core dependencies (SQLite-backed KV store)
    const coreDeps = await makeWebsocketServerCoreDependenciesWithSqlite();

    // Initialize Hono app with WebSocket support
    const { app, injectWebSocket, nodeAppDependencies } = initApp(coreDeps);

    // Get port from environment or use default
    const port = parseInt(process.env.PORT || '1337', 10);

    // Start the HTTP server
    server = serve({
      fetch: app.fetch,
      port,
    }, (info) => {
      console.log(`Server listening on http://localhost:${info.port}`);
    });

    // Inject WebSocket support into the server
    injectWebSocket(server);

    // Start the Springboard engine
    await startNodeApp(nodeAppDependencies);
    console.log('Node application started successfully');
  } catch (error) {
    console.error('Failed to start node server:', error);
    throw error;
  }
}

/**
 * Stop the node server
 */
export async function stop() {
  if (!server) {
    return;
  }

  return new Promise<void>((resolve, reject) => {
    const timeout = setTimeout(() => {
      reject(new Error('Server close timeout'));
    }, 5000);

    server!.close((err) => {
      clearTimeout(timeout);
      if (err) {
        reject(err);
      } else {
        console.log('Server stopped successfully');
        server = null;
        resolve();
      }
    });
  });
}

// HMR support: clean up before module reload
if (import.meta.hot) {
  import.meta.hot.dispose(async () => {
    console.log('[HMR] Stopping server before reload...');
    await stop();
  });
}
