import { serve } from '@hono/node-server';
import { initApp, makeWebsocketServerCoreDependenciesWithSqlite } from 'springboard/server';
import { startNodeApp } from 'springboard/platforms/node';
import '__USER_ENTRY__';

/**
 * Self-contained Node.js server entrypoint
 *
 * This file is generated by the Springboard Vite plugin and serves as the
 * entry point for the Node.js dev server. It:
 *
 * 1. Imports the user's application entry (which registers modules)
 * 2. Creates SQLite-backed core dependencies
 * 3. Initializes the Hono app with WebSocket support
 * 4. Starts the HTTP server
 * 5. Injects WebSocket handler
 * 6. Starts the Springboard engine
 * 7. Sets up graceful shutdown handlers
 */

(async () => {
  try {
    // Create core dependencies (SQLite-backed KV store)
    const coreDeps = await makeWebsocketServerCoreDependenciesWithSqlite();

    // Initialize Hono app with WebSocket support
    const { app, injectWebSocket, nodeAppDependencies } = initApp(coreDeps);

    // Get port from environment or use default
    const port = parseInt(process.env.PORT || '1337', 10);

    // Start the HTTP server
    const server = serve({
      fetch: app.fetch,
      port,
    }, (info) => {
      console.log(`Server listening on http://localhost:${info.port}`);
    });

    // Inject WebSocket support into the server
    injectWebSocket(server);

    // Start the Springboard engine
    await startNodeApp(nodeAppDependencies);
    console.log('Node application started successfully');

    // Note: We don't set up SIGINT/SIGTERM handlers here because this code
    // runs inside the Vite dev server process. Vite handles shutdown signals
    // and will clean up when the process exits.
  } catch (error) {
    console.error('Failed to start node server:', error);
    process.exit(1);
  }
})();
