import { serve } from '@hono/node-server';
import { initApp, makeWebsocketServerCoreDependenciesWithSqlite } from 'springboard/server';
import { startNodeApp } from 'springboard/platforms/node';

/**
 * Self-contained Node.js server entrypoint
 *
 * This file is generated by the Springboard Vite plugin and serves as the
 * entry point for the Node.js dev server. It:
 *
 * 1. Creates SQLite-backed core dependencies
 * 2. Initializes the Hono app with WebSocket support
 * 3. Starts the HTTP server
 * 4. Injects WebSocket handler
 * 5. Starts the Springboard engine
 * 6. Sets up graceful shutdown handlers
 *
 * Note: User entry file is not needed here - modules are registered in the browser.
 */

(async () => {
  try {
    // Create core dependencies (SQLite-backed KV store)
    const coreDeps = await makeWebsocketServerCoreDependenciesWithSqlite();

    // Initialize Hono app with WebSocket support
    const { app, injectWebSocket, nodeAppDependencies } = initApp(coreDeps);

    // Get port from environment or use default
    const port = parseInt(process.env.PORT || '1337', 10);

    // Start the HTTP server
    const server = serve({
      fetch: app.fetch,
      port,
    }, (info) => {
      console.log(`Server listening on http://localhost:${info.port}`);
    });

    // Inject WebSocket support into the server
    injectWebSocket(server);

    // Start the Springboard engine
    await startNodeApp(nodeAppDependencies);
    console.log('Node application started successfully');

    // Set up graceful shutdown handlers
    let isShuttingDown = false;
    const shutdown = () => {
      if (isShuttingDown) return;
      isShuttingDown = true;
      console.log('Received shutdown signal, closing server...');
      server.close(() => {
        console.log('Server closed successfully');
        process.exit(0);
      });
    };

    process.on('SIGTERM', shutdown);
    process.on('SIGINT', shutdown);
  } catch (error) {
    console.error('Failed to start node server:', error);
    process.exit(1);
  }
})();
