#!/bin/bash

if [ -n "$1" ]; then
  version="$1"
  full_version="${version#v}"
else
  full_version="0.15.0-rc9"
fi

PUBLISH_MODE="verdaccio"
PACKAGES="all"

shift # Skip the first argument (version)
while [[ $# -gt 0 ]]; do
  case "$1" in
    --mode)
      PUBLISH_MODE="$2"
      shift 2
      ;;
    --packages)
      PACKAGES="$2"
      shift 2
      ;;
    *)
      echo "Unknown option: $1"
      exit 1
      ;;
  esac
done

# Validate mode
if [[ "$PUBLISH_MODE" != "npm" && "$PUBLISH_MODE" != "verdaccio" ]]; then
  echo "Error: --mode must be either 'npm' or 'verdaccio'"
  exit 1
fi

set -e
root_dir=$(pwd)

should_process_package() {
  local package_name=$1

  if [[ "$PACKAGES" == "all" ]]; then
    return 0
  fi

  IFS=',' read -ra selected_packages <<< "$PACKAGES"
  for selected_package in "${selected_packages[@]}"; do
    if [[ "$selected_package" == "$package_name" ]]; then
      return 0
    fi
  done

  return 1
}

bump_package_version() {
  local package_name=$1
  local target_dir=$2

  if should_process_package "$package_name"; then
    bump_version "$target_dir"
  fi
}

publish_selected_package() {
  local package_name=$1
  local target_dir=$2

  if should_process_package "$package_name"; then
    publish_package "$target_dir"
    sleep 1
  fi
}

reset_package_version() {
  local package_name=$1
  local target_dir=$2

  if should_process_package "$package_name"; then
    reset_version "$target_dir"
  fi
}

bump_version() {
  local target_dir=$1
  local version=$full_version

  cd "$target_dir" || exit 1
  echo "Bumping version in $target_dir"
  jq --arg version "$version" '.version = $version' "$target_dir/package.json" > "$target_dir/tmp.json" && mv "$target_dir/tmp.json" "$target_dir/package.json"
}

reset_version() {
  local target_dir=$1
  local version=$full_version

  cd "$target_dir" || exit 1
  echo "Resetting version in $target_dir"
  jq --arg version "0.0.1-autogenerated" '.version = $version' "$target_dir/package.json" > "$target_dir/tmp.json" && mv "$target_dir/tmp.json" "$target_dir/package.json"
}

publish_package() {
  local target_dir=$1
  cd "$target_dir" || exit 1
  echo "Publishing package in $target_dir"

  local environment=""

  # Set registry based on mode
  if [ "$PUBLISH_MODE" = "npm" ]; then
    environment="npm"
  else
    export NPM_CONFIG_REGISTRY="http://localhost:4873"
    # export NPM_CONFIG_REGISTRY="http://10.0.1.1:4873"
    environment="local Verdaccio"
  fi

  # Determine tag based on version format
  local tag="latest"
  if [[ "$full_version" == *"-"* ]]; then
    if [[ "$full_version" == *"-rc"* ]]; then
      tag="rc"
    elif [[ "$full_version" == *"-dev"* ]]; then
      tag="dev"
    else
      tag="dev"
    fi
    echo "Publishing pre-release version to $environment with tag: $tag"
  else
    echo "Publishing production version to $environment"
  fi

  # Execute the publish command
  pnpm publish --access public --tag "$tag" --no-git-checks
}

# Core packages
bump_package_version "springboard" "$root_dir/packages/springboard"
bump_package_version "jamtools-core" "$root_dir/packages/jamtools/core"
bump_package_version "jamtools-features" "$root_dir/packages/jamtools/features"

# CLI and tooling
# bump_package_version "springboard-cli" "$root_dir/packages/springboard/cli"
bump_package_version "create-springboard-app" "$root_dir/packages/springboard/create-springboard-app"
bump_package_version "springboard-vite-plugin" "$root_dir/packages/springboard/vite-plugin"

# External integrations
bump_package_version "springboard-mantine" "$root_dir/packages/springboard/external/mantine"
bump_package_version "springboard-shoelace" "$root_dir/packages/springboard/external/shoelace"
bump_package_version "@springboardjs/template-react-native" "$root_dir/packages/springboard/platform-templates/react-native-caz"

# Publish core packages first (dependencies)
publish_selected_package "springboard" "$root_dir/packages/springboard"
publish_selected_package "jamtools-core" "$root_dir/packages/jamtools/core"

# publish_selected_package "jamtools-features" "$root_dir/packages/jamtools/features"
# publish_selected_package "springboard-vite-plugin" "$root_dir/packages/springboard/vite-plugin"
# publish_selected_package "springboard-mantine" "$root_dir/packages/springboard/external/mantine"
# publish_selected_package "springboard-shoelace" "$root_dir/packages/springboard/external/shoelace"
# publish_selected_package "springboard-cli" "$root_dir/packages/springboard/cli"

# Publish CLI and tooling last (likely depend on core packages)
publish_selected_package "create-springboard-app" "$root_dir/packages/springboard/create-springboard-app"
publish_selected_package "@springboardjs/template-react-native" "$root_dir/packages/springboard/platform-templates/react-native-caz"

# Core packages
reset_package_version "springboard" "$root_dir/packages/springboard"
reset_package_version "jamtools-core" "$root_dir/packages/jamtools/core"
reset_package_version "jamtools-features" "$root_dir/packages/jamtools/features"

# CLI and tooling
# reset_package_version "springboard-cli" "$root_dir/packages/springboard/cli"
reset_package_version "create-springboard-app" "$root_dir/packages/springboard/create-springboard-app"
reset_package_version "springboard-vite-plugin" "$root_dir/packages/springboard/vite-plugin"

# External integrations
reset_package_version "springboard-mantine" "$root_dir/packages/springboard/external/mantine"
reset_package_version "springboard-shoelace" "$root_dir/packages/springboard/external/shoelace"
reset_package_version "@springboardjs/template-react-native" "$root_dir/packages/springboard/platform-templates/react-native-caz"
